language: objective-c
before_script:
- brew update
- brew upgrade xctool || true
script: xctool test -project ASBPlayerSubtitlingTests/ASBPlayerSubtitlingTests.xcodeproj -scheme ASBPlayerSubtitlingTests -sdk iphonesimulator